Feature/about
KlaudiaKrekora/team-project-IceCream pull request #13
Opened 2023-01-27 16:32 UTC by KarolTrombala

2023-01-27 22:30 UTC, KlaudiaKrekora requested changes

2023-01-27 22:30 UTC, KlaudiaKrekora commented on src/partials/about.html
> +  <label class="section-about__heading-label">Tradition and love</label>
tutaj nazwą klasy wystarczy, że będzie "section-about__label". Poza tym świetnie!

2023-01-29 20:45 UTC, KarolTrombala commented on src/partials/about.html
> +  <label class="section-about__heading-label">Tradition and love</label>
poprawione

2023-01-29 20:46 UTC, KlaudiaKrekora approved these changes

2023-01-29 20:46 UTC, merged