Feature/advantage scss + change html
KlaudiaKrekora/team-project-IceCream pull request #15
Opened 2023-01-27 17:00 UTC by cmdspeed

mobile

2023-01-27 22:42 UTC, KlaudiaKrekora requested changes

2023-01-27 22:42 UTC, KlaudiaKrekora commented on src/sass/partials/advantages.scss
> +    &__heading-hiden {
tutaj, jak i w html poprawiłabym literówkę, która później może wprowadzić w błąd. "hidden"

2023-01-27 22:42 UTC, KlaudiaKrekora commented on src/sass/partials/advantages.scss
> +.advantages__second-heading--image1::before {
w nazwach klas nie powinniśmy zawierać cyfr, a jedynie opis. W związku z tym w mixins zamiast np. "....--image1" dałabym "---img-first". Uprzejmie proszę o poprawki w koniecznych miejscach :)

2023-01-28 10:05 UTC, cmdspeed commented on src/sass/partials/advantages.scss
> +.advantages__second-heading--image1::before {
już poprawione :)

2023-01-28 14:29 UTC, KlaudiaKrekora approved these changes
Super się spisałeś!

2023-01-28 14:29 UTC, merged